name: Pickle
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  Pickle:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
    frameworks:
      - Quartz
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.test.Pickle
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_FILE: Sources/Info.plist
      CODE_SIGN_ENTITLEMENTS: Sources/Pickle.entitlements
      MACOSX_DEPLOYMENT_TARGET: "14.0"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: Pickle
        CFBundleDisplayName: Pickle
        CFBundleIdentifier: com.test.Pickle
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1"
        LSMinimumSystemVersion: "14.0"
        NSUserNotificationAlertStyle: alert
