name: Pickle
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages:
  TelemetryDeck:
    url: https://github.com/TelemetryDeck/SwiftSDK
    from: 2.3.0

targets:
  Pickle:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
        excludes:
          - Tests/**
    resources:
      - path: Sources/Assets.xcassets
    frameworks:
      - Quartz
    dependencies:
      - package: TelemetryDeck
        product: TelemetryDeck
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.pickleformac.pickle
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_FILE: Sources/Info.plist
      CODE_SIGN_ENTITLEMENTS: Sources/Pickle.entitlements
      MACOSX_DEPLOYMENT_TARGET: "14.0"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: PickleApp
        CFBundleDisplayName: PickleApp
        CFBundleIdentifier: app.pickleformac.pickle
        CFBundleVersion: "5"
        CFBundleShortVersionString: "1.1"
        LSMinimumSystemVersion: "14.0"
        LSUIElement: true
        NSUserNotificationAlertStyle: alert

  PickleTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/Tests
    frameworks:
      - XCTest
    dependencies:
      - target: Pickle
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.pickleformac.pickleTests
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      GENERATE_INFOPLIST_FILE: YES
